### ISSUE TITLE
Remove body field from node / block forms for drag and drop content

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/lightning_dxpr#15]
The node form often causes problems with the HTML generated by our layout builder. Also, people get confused if they add images with CKEditor and they won't work work in the front-end if DXPR Builder is enabled.

We should still fix bugs that arise in the node form like #14  because sometimes the node form is needed for debugging. But the default body/node form in lightning_dxpr should switch to hide the body field.

Please test that creating content still works OK after this change.

@mhmelshaaerdxpr I would like you to be reviewer on this PR and test that the fix works OK that @dench0 creates. This will involve creating a fresh installation based of his feature branch.

**Comment by dench0** [comment]
@jjroelofs do you want to hide the `body` field only for the `lightning_dxpr` profile because maybe it better to hide it for the `dxpr_builder` submodules (`dxpr_builder_page` and `dxpr_builder_block`): https://github.com/dxpr/dxpr_builder/blob/300615ec46ca66cda680bf33a67c3083bf3eea92/modules/dxpr_builder_page/config/optional/core.entity_form_display.node.drag_and_drop_page.default.yml#L46

**Comment by jjroelofs** [comment]
@dench0 yeah OK let's do that
