### ISSUE TITLE
Lightning to reach end-of-life

### ISSUE THREAD

**Issue by phenaproxima** [dxpr/lightning_dxpr#26]
Hi there :) I'm the Lightning maintainer at Acquia, and I see that this appears to be an actively maintained sub-profile of Lightning. I thought I would drop in to inform you that Lightning is going to reach its end of life in November 2021 (see https://www.acquia.com/blog/acquia-lightning-eol-2021-acquia-cms-future), and therefore this package will probably need to drop its Lightning dependency and decouple the sub-profile by then. There is some documentation on how to do that available at https://github.com/acquia/lightning/wiki/Uninstalling-Lightning#decoupling-a-sub-profile-from-lightning. Please let me know if I can be of any assistance!

**Comment by jjroelofs** [comment]
Thank you Adam. I'm the founder and product manager of DXPR. 

Our main goal with this project is to support Acquia Lightning users who wish to use our DXPR Layout Builder instead of, or in addition to,  Drupal core's layout builder or Acquia Site Studio. If Lightning will become obsolete so will this profile.

As many of our clients are Acquia clients we would like to continue developing a sub-profile on Acquia CMS. Is it possible we can spin up Acquia CMS without being a paying Acquia client ourselves? @phenaproxima 

Can you tell me who is the product manager for Acquia CMS? I am interested in talking to the PM to discuss any possible collaboration.

**Comment by phenaproxima** [comment]
The best person to talk to about Acquia CMS is probably @msherron. He would definitely be able to answer all questions. As far as I know, Acquia CMS doesn't support sub-profiling (for a whole mess of reasons), but I do know that there's an effort to make it "composable", so that you can bring its functionality into another project piecemeal, _without_ needing to use Site Studio. But Michael can probably answer more questions than I can!

**Comment by jjroelofs** [comment]
Thanks again @phenaproxima, also for updating lightning_media with the asset-packagist removal. I'll close this issue since we have found ways to work around the unmaintained status of Lightning.
